name: the_furniture_house
description: A new Flutter application.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker:
  cupertino_icons: ^1.0.0
  getflutter:
  expansion_tile_card:
  flutter_svg:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/logo.jpeg
    - images/onboard1.jpeg
    - images/onboard2.jpeg
    - images/onboard3.jpeg
    - images/logged.jpg
    - images/kitchen.jpeg
    - images/Kitchen 111.jpeg
    - images/Kitchen 112.jpeg
    - images/Kitchen 121.jpeg
    - images/Kitchen 122.jpeg
    - images/Kitchen 131.jpeg
    - images/Kitchen 132.jpeg
    - images/Kitchen 141.jpeg
    - images/Kitchen 142.jpeg
    - images/Kitchen 151.jpeg
    - images/Kitchen 152.jpeg
    - images/Kitchen 211.jpeg
    - images/Kitchen 212.jpeg
    - images/Kitchen 221.jpeg
    - images/Kitchen 222.jpeg
    - images/Kitchen 231.jpeg
    - images/Kitchen 232.jpeg
    - images/Kitchen 241.jpeg
    - images/Kitchen 242.jpeg
    - images/Kitchen 251.jpeg
    - images/Kitchen 252.jpeg
    - images/Kitchen 311.jpeg
    - images/Kitchen 312.jpeg
    - images/Kitchen 321.jpeg
    - images/Kitchen 322.jpeg
    - images/Kitchen 331.jpeg
    - images/Kitchen 332.jpeg
    - images/Kitchen 341.jpeg
    - images/Kitchen 342.jpeg
    - images/Kitchen 351.jpeg
    - images/Kitchen 352.jpeg
    - images/Living Room.jpeg
    - images/Dining Hall.jpeg
    - images/Office.jpeg
    - images/Study Room.jpeg
    - images/Bedroom.jpeg
    - images/Living 111.jpeg
    - images/Living 121.jpeg
    - images/Living 131.jpeg
    - images/Living 141.jpeg
    - images/Living 151.jpeg
    - images/Living 211.jpeg
    - images/Living 221.jpeg
    - images/Living 231.jpeg
    - images/Living 241.jpeg
    - images/Living 251.jpeg
    - images/Living 311.jpeg
    - images/Living 321.jpeg
    - images/Living 331.jpeg
    - images/Living 341.jpeg
    - images/Living 351.jpeg
    - images/Bed 111.jpeg
    - images/Bed 121.jpeg
    - images/Bed 131.jpeg
    - images/Bed 141.jpeg
    - images/Bed 151.jpeg
    - images/Bed 211.jpeg
    - images/Bed 221.jpeg
    - images/Bed 231.jpeg
    - images/Bed 241.jpeg
    - images/Bed 251.jpeg
    - images/Bed 311.jpeg
    - images/Bed 321.jpeg
    - images/Bed 331.jpeg
    - images/Bed 341.jpeg
    - images/Bed 351.jpeg

